export const CATEGORY_LABELS: Record<string, string> = {
  ITALIAN: "Italiana",
  FRENCH: "Francesa",
  INTERNATIONAL: "Internacional",
  ASIAN: "Asiática",
  CRIOLLA: "Criolla",
  STEAKHOUSE: "Steakhouse",
  SEAFOOD: "Mariscos",
  FAST_FOOD: "Comida rápida",
  CAFE_DESSERTS: "Café y postres",
  PIZZERIA: "Pizzería",
  SUSHI: "Sushi",
  BAR_PUB: "Bar",
  VEGETARIAN: "Vegetariana",
  HAIR_SALON: "Peluquería",
  NAIL_SALON: "Salón de uñas",
  SPA_WELLNESS: "Spa y bienestar",
  BARBERSHOP: "Barbería",
  OTHER_SERVICES: "Otros servicios",
};
